/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.b14w4r;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FinanceManagerTest {
    @Test void appHasAGreeting() {
        FinanceManager classUnderTest = new FinanceManager();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
